spring.application.name=banking

# linking the banking database
spring.datasource.url = jdbc:postgresql://localhost:5432/banking
spring.datasource.username = postgres
spring.datasource.password = postgres